[package]
name = "endors"
description = "Validation library"
version = "0.1.0"
edition = "2021"
license = "MIT"
homepage = "https://github.com/jusexton/endors/"
repository = "https://github.com/jusexton/endors/"
readme = "README.md"

[dependencies]
thiserror = "1.0.65"
